name: DevSecOps CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  helm-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Helm Lint
        run: |
          helm lint kubernetes/helm/user-service

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build \
          -t user-service:${{ github.sha }} \
          applications/user-service

  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build \
          -t user-service:${{ github.sha }} \
          applications/user-service

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: user-service:${{ github.sha }}
          format: table
